name: boilerplate-frontend

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  boilerplate_frontend:
    name: boilerplate-frontend
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - name: （デバッグ用）Payload (GITHUB_EVENT_PATH) を確認する
        run: |
          cat $GITHUB_EVENT_PATH
      - name: （デバッグ用）inputs と secrets と github と env を確認する
        run: |
          echo '${{ toJson(inputs) }}'
          echo '${{ toJson(secrets) }}'
          echo '${{ toJson(github) }}'
          echo '${{ toJson(env) }}'
      - name: （デバッグ用）env を確認する
        run: |
          echo '${{ toJson(env) }}'
      - name: コードをチェックアウトする
        uses: actions/checkout@v5
      - name: pnpm のセットアップを行う
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        with:
          version: 10.17.0
      - name: Node.js のセットアップを行う
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - name: Node のパッケージをインストールする
        run: |
          pnpm install
      - name: （デバッグ用）各種バージョンを確認する
        run: |
          echo "gh version: $(gh version)"
          echo "docker --version: $(docker --version)"
          echo "docker-compose --version: $(docker-compose --version)"
          echo "node --version: $(node --version)"
          echo "npm --version: $(npm --version)"
          echo "npm list: $(npm list)"
          echo "npm list -g: $(npm list -g)"
          echo "yarn --version: $(yarn --version)
          echo "npx --version: $(npx --version)
      - name: TypeScript をコンパイルする
        run: |
          pnpm build
      - name: ESLint を実行する
        # TODO: .ts に対して実行するようにする
        run: |
          pnpm eslint --no-config-lookup --debug
      - name: Prettier を実行する
        run: |
          pnpm prettier src/app.ts
      - name: Stylelint を実行する
        run: |
          pnpm stylelint src/app.css
